apiVersion: batch/v1
kind: CronJob
metadata:
  name: etm
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: every-three-minute
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo date
          restartPolicy: OnFailure