apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: podsa:podcr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podcr
subjects:
- kind: ServiceAccount
  name: podsa
  namespace: default
