apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbUZ1WlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUp5YmFBQWFTVXlzbno2RDBUR0xzOHA4Wm1ldzkrMkZIK0E1OXBqMVNTdDVWOE1nClhqRU5DNy9CWXBTTHpFdWVLc0ZxaWV3N01udHVVS3VKYUsxdEh3TmFVR2hPekxncWNkVFRlblp4aTdrUG1UZEsKY2JheGJ6ODU5ZDd2L1Q3SThCakUwRXVMNVZOa29ud29xTjY5Qk50TW1KSk9Demx2aEZXRFFMTS9hTlcxcUVSMAo2emVMbWJKdjlsYTVnOGppeExwTFlCZXVBdlBtNlJCa080bmNtRU5iYm9HbWE5L1hCTS94Vmd2aVVBQXFIVUpYCkFRT3JodWFaU3cwbUtaQnlML2FPbzg1bjBpQldXZXhCOEdJbUZ5SVFPYWFta1VmQWxuSXRUN2s3bDZvZFdnbGIKaFVCN0h1aWRNRkw1ZWRmN2RXRlVxelNCelFZSWZlZFQyME5vdkU4Q0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQWRHSWlKWThMUXF0dlNUMlZjWndRTkNWYi9QYmxqOWNHUmhOU3hBZjNWWVZMc214ZTlrK1M3CnFYQjIwa0VlU3BOOVZPMFBHNjhiWXFzK29leWdlbWdhZXM1T1VLWlFGWFU4VytPZVVvTjhINUYwcEFtVlNFY0sKWXd6bWQxb2lNQjg1cTh1OTlMNkhUcjFPUWpnUDFzaFQvTXF6eUFrTjhDTm44Q1FBQ2ppVnMzR28wbHZTWDc2Vgo1OURqVHBobmhpc1JBYjFLV041Y3RVTDQ2Ym8rSE5mM3ZzWEZTTmRBQ2NTdUptN1dqZjRzMkdEY2pubzlFYXJRClZmQW1uUXhlZFJIaWYrYko1WW9na1pxK0ZCcTdBYTJQMzA4R1lsdzdwOHdEVDJYdXkxSzJueWo5NmRlMTBjcC8KVW5RZElYQU1WMGJ2TXNlWVpDVlpyVkMzQ3ppY0IyakEKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client