apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  labels:
    name: pod-with-secret
spec:
  containers:
  - name: pod-with-secret
    image: pod-with-secret
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret
    env:
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_Password

    volume:
      - name: app-secret-volume
        secret: 
          secretName: app-secret


    


