apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
  labels:
    name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper-pod
    image: ubuntu-sleeper
    command: ["sleep2.0"]   # this field overrides the ENTRYPOINT instruction of the Dockerfile
    args: ["10"]            # CMD instruction is overriden here
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"


