apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
 


