---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: talex-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 52Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ruby-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 78Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"