apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
  labels:
    name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
    args: 
      - "shuf -i 0-100 -n 1 >> /opt/number.out;"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8383
    volumes:
    - name: data-volume
      awsElasticBlockStore:
        volumeID: <volume-id>
        fsType: ext4
