apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: box
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["sh", "-c", "sleep 99999"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
