apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    daitya96/tier: frontend
  name: nginx-https
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 31111
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
