apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pdfdocuments.k8s.startkubernetes.com
spec:
  group: k8s.startkubernetes.com
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties: 
            spec:
              type: object
              properties:
                documentName:
                  type: string
                text:
                  type: string
  names:
    kind: PdfDocument
    singular: pdfdocument
    plural: pdfdocuments
    shortNames:
      - pdf
      - pdfs