apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80    # port where the backend is exposed
      port: 80          # port where the service is exposed
      nodePort: 30008